import { Roboto } from 'next/font/google';
import './globals.css';
<<<<<<< HEAD
import Header from "src/components/layout/Header";
import {SessionProvider} from "next-auth/react";
import {AppProvider} from "@/components/AppContext";
=======

import {SessionProvider} from "next-auth/react";
import {AppProvider} from "../components/AppContext";
import Header from "../components/layout/Header";

>>>>>>> 1870973580709f1d312463a6f8393c0093d12199

const roboto = Roboto({ subsets: ['latin'] , weight: ['400', '500', '700']})

export const metadata = {
  title: 'Gloverse',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
      <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
              <Header />
              {children}
              <footer className="border-t p-8 text-center text-grey-500 mt-16">
                  &copy; 2023 All rights reserved
              </footer>
          </AppProvider>
      </main>
      </body>
    </html>
=======
      <html lang="en" className="scroll-smooth">
      <body className={roboto.className}>
      <main className="max-w-4xl mx-auto p-4">
        <AppProvider>
          <Header />
          {children}
          <footer className="border-t p-8 text-center text-grey-500 mt-16">
            &copy; 2023 All rights reserved
          </footer>
        </AppProvider>
      </main>
      </body>
      </html>
>>>>>>> 1870973580709f1d312463a6f8393c0093d12199
  )
}
